### ISSUE TITLE
FrozenStringLiteral breaks puppet module

### ISSUE THREAD

**Issue by laugmanuel** [voxpupuli/puppet-posix_acl#104]
The introduction of FrozenStringLiteral made yesterday (2022-01-20) to comply with Rubocop defaults causes Puppet catalog compilation errors.

## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: Agent 6.26.0 / Puppetserver 6.18.0
- Ruby: Agent 2.5.9p229 / Puppetserver jruby 9.2.17.0 (2.5.8)
- Distribution: Agent RHEL 8.5 / Puppetserver RHEL 7.9
- Module version: latest/master

## How to reproduce (e.g Puppet code you use)
```puppet
class acl_testing_class {
  file { '/var/log/acl_test':
    ensure => directory,
  }

  posix_acl { '/var/log/acl_test':
    action     => set,
    permission => [
      'user::rwx',
      'group::rwx',
      'other::rwx',
      'default:user::rwx',
      'default:group::rw-',
      'default:other::rw-',
    ],
    provider   => posixacl,
    recursive  => false,
  }
}

```

## What are you seeing
Errors during catalog compilation

## What behaviour did you expect instead
Successfully compilation of catalog

## Output log
```sh
Failed to apply catalog: Parameter permission failed on Posix_acl[/var/log/acl_test]: Munging failed for value "default:user::rwx" in class permission: can't modify frozen String (file: /etc/puppetlabs/code/environments/production/modules/service_module/manifests/init.pp, line: 56)
```

## Any additional information you'd like to impart
When reverting back to commit af9fdf8330b1c438fb99bcc18da178fda2641d7f , the module works again

**Comment by ekohl** [comment]
In https://github.com/voxpupuli/puppet-posix_acl/pull/103 some code is written to avoid using mutable strings. I believe @bastelfreak is fighting with his environment to run the acceptance tests locally.

**Comment by bastelfreak** [comment]
Hi @laugmanuel,
can you try the code from https://github.com/voxpupuli/puppet-posix_acl/pull/103 please?

**Comment by laugmanuel** [comment]
Hi @bastelfreak,
i've improved the example code above. I'm using a puppet managed directory resource.
Testing #103 looks very promising:
```yaml
Notice: /Stage[main]/Testing_module/File[/var/log/acl_test]/ensure: created
Notice: /Stage[main]/Testing_module/Posix_acl[/var/log/acl_test]/permission: permission changed ["group::r-x", "other::r-x", "user::rwx"] to ["default:group::rw-", "default:other::rw-", "default:user::rwx", "group::rwx", "other::rwx", "user::rwx"]
```

**Comment by ekohl** [comment]
In #107 I tried to rewrite the code a bit further and also fixed specifying it in octal mode (that was plain broken).

**Comment by bastelfreak** [comment]
I verified that #107 fixed it.
