### ISSUE TITLE
Move to Vox Pupuli

### ISSUE THREAD

**Issue by roidelapluie** [voxpupuli/puppet-posix_acl#29]
What do you think about moving puppet-acl to Vox Pupuli to get more people working on it, and get higher visibility plus better standards?

**Comment by dobbymoodge** [comment]
That sounds reasonable; I'll look into what's involved later this morning.

**Comment by roidelapluie** [comment]
It is there: https://voxpupuli.org/docs/

**Comment by dobbymoodge** [comment]
I suspect we should resolve https://github.com/dobbymoodge/puppet-acl/issues/26 first. Any idea on how we could do that without breaking existing deployments?

**Comment by roidelapluie** [comment]
The only way to do #26 is by bumping major version so pple will know it's breaking

**Comment by roidelapluie** [comment]
puppet-posixacl and posix_acl type?

**Comment by dobbymoodge** [comment]
sounds good to me

**Comment by roidelapluie** [comment]
Well this module is not meant to be only for posix acl, so I think keeping acl is fine ?

**Comment by claflico** [comment]
@roidelapluie Does that mean that enhancements this module will be capable of what the puppetlabs/acl Windows module does?

**Comment by tequeter** [comment]
I don't think keeping acl is fine: until the module and its type are renamed, #26 will be a blocking issue for multi-platform shops. I'll have to fork this module and rename the day I need to manage Windows ACLs on the same Puppet server.

If you have a strong opinion on supporting Windows ACL (or some other breed of ACL?), then at the very least make it "acl2". But IMHO it is fine to have this module as a POSIX specialist.

**Comment by roidelapluie** [comment]
ok guys. 

posix_acl it will be then.

**Comment by dobbymoodge** [comment]
@roidelapluie I still haven't gotten started on this, unfortunately. I'll try to get working on #26 this weekend, but if you have something in some stage of development, you could add it as a branch on this repo and we could finish it together.

**Comment by dobbymoodge** [comment]
@roidelapluie actually I think `file_acl` would be a better name.

**Comment by ekohl** [comment]
Any progress on this? It looks like we might need a module to maintain ACLs in the foreman installer and this I could help if needed.

**Comment by dobbymoodge** [comment]
@ekohl Real Life and Paying Work have kept this task at the bottom of my list. If you want to submit a PR for the module rename, that would help things move along a bit though. :D

**Comment by vandelin586** [comment]
What are people using in the interim for a solution ?

**Comment by dobbymoodge** [comment]
@vandelin586 I don't know what alternatives exist. I'm really sorry I've let this issue dangle for over a year now. I've just merged #33 so if anyone wants to help with the next steps, I'd be thrilled. For now I'm still pretty much underwater with my Real Job so I'm not sure when I'll have time to invest in this particular issue :(

**Comment by vandelin586** [comment]
If I knew where to start or what to do , I would try my best. A person I work with copied this code and redesigned the naming so that the module named was not acl as puppetlabs-acl is. Just changing the module name was not all that is involved and this did not work, I believe what I seen in your latest merge #33 is more of what we need. or perhaps a combination of the two. When trying to use your most recent type name posix_acl I get back an error saying could not find class acl::requirements  

I dont know , im a newb at this stuff , I will work hard at trying to understand it over this next weekend, right now setting linux acl is a show stopper for me, might revert to some exec or something if I cant figure anything out

**Comment by vandelin586** [comment]
nevermind posix_acl type works just had stale data from the older module

**Comment by ekohl** [comment]
@dobbymoodge I can help with the migration aspect of it and send some PRs to update code but you'll have to do the github transfer and upload a module on the forge that states it's deprecated.

**Comment by bastelfreak** [comment]
Hi @dobbymoodge, I sent you an invitation to the Vox Pupuli org on github. After accepting it, you're able to migrate the repositoy.

**Comment by claflico** [comment]
@bastelfreak I'm moving on from Puppet. Can I get an invite too so I can migrate my winlogbeat repo?

**Comment by bastelfreak** [comment]
@claflico invited you as well. Feel free to join our IRC channel #voxpupuli on freenode for further discussions.

**Comment by ekohl** [comment]
Looks like this has been resolved now.

**Comment by crispygoth** [comment]
This issue got closed and a 0.0.5 release has been tagged on GitHub, but I can't seem to see a voxpupuli release on the Forge? https://forge.puppet.com/puppet/posix_acl gives a "page not found" error. Is there something that needs doing to make it appear there?

**Comment by bastelfreak** [comment]
@crispygoth it is now available: https://forge.puppet.com/puppet/posix_acl
