### ISSUE TITLE
Solaris support

### ISSUE THREAD

**Issue by rssh22** [voxpupuli/puppet-posix_acl#32]
Hello!

I think it would be easy to add Solais OS support just by taking car of some issues related with getfacl and setfacl specific commands in that OS.

For example, getfacl command under Solaris does not support --absolute-names neither --no-efective arguments.

Is there any chance that you fix this problem. Could I collaborate somehow?

Kind Regards,

Raúl

**Comment by dobbymoodge** [comment]
Looking into this, it seems like Solaris ACLs are based on POSIX.1e, so it should be more-or-less possible. @rssh22 do you think the Illumos-based distros (like [DilOS](http://www.dilos.org/)) are similar enough to Solaris to develop/test this feature on?

**Comment by rssh22** [comment]
Hello!

I've installed dilos 1.3.4 i386 and it looks pretty similar to Solaris OS. So I think it could be possible to make the tests on it.

**Comment by ghoneycutt** [comment]
Closing due to age of issue. Please re-open with a pull request if you would like this enhancement.
