### ISSUE TITLE
File is executable when X option is set on directory

### ISSUE THREAD

**Issue by grodriguezl** [voxpupuli/puppet-posix_acl#64]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 6.7.2
- Ruby:
- Distribution: CentOS 7
- Module version: Last commit, after fe6c5ca6f84bf918703f17f6aa3d9bf4362891ac

## Scenario

Hi
I have this directory with the following permissions:
```
ls -l /backup2
total 0
-rw-r--r--. 1 root     root      0 ago  2 15:40 file0
drwx------. 2 postgres postgres 19 ago  2 15:40 test1
drwx------. 2 root     root      6 ago  2 15:39 test2
```

## How to reproduce (e.g Puppet code you use)
```
posix_acl { "/backup2":
    action     => set,
    permission => [
      'user:syncuser:rwX',
      'mask::rwX',
    ],
    recursive  => true,
   }
```

## What are you seeing
File /backup2/file0 is executable

```
getfacl file0
# file: file0
# owner: root
# group: root
user::rw-
user:syncuser:rwx
group::r--
mask::rwx
other::r--
```

## What behaviour did you expect instead
File /backup2/file0 is not executable.
I would expect every file inside /backup2 to be not executable and every dir inside /backup executable.
```
getfacl file0
# file: file0
# owner: root
# group: root
user::rw-
user:syncuser:rw-
group::r--
mask::rw-
other::r--
```
## Debug log
```
Executing: '/usr/bin/setfacl -R -n -m user:syncuser:rwx /backup2'
Executing: '/usr/bin/setfacl -R -n -m mask::rwx /backup2'

```

## Any additional information you'd like to impart

If I run `setfacl -n -R -m u:syncuser:rwX /backup2` and `setfacl -n -R -m m::rwX /backup2` manually the result is the expected one with file0 being not executable

**Comment by ekohl** [comment]
Fixed in https://github.com/voxpupuli/puppet-posix_acl/pull/61 but unreleased.

**Comment by grodriguezl** [comment]
I am using the latest and unreleased version from master branch (after #61).

This line https://github.com/voxpupuli/puppet-posix_acl/blob/fe6c5ca6f84bf918703f17f6aa3d9bf4362891ac/lib/puppet/provider/posix_acl/posixacl.rb#L91
changes X to x for comparison purposes. 

Later 
https://github.com/voxpupuli/puppet-posix_acl/blob/fe6c5ca6f84bf918703f17f6aa3d9bf4362891ac/lib/puppet/provider/posix_acl/posixacl.rb#L92
https://github.com/voxpupuli/puppet-posix_acl/blob/fe6c5ca6f84bf918703f17f6aa3d9bf4362891ac/lib/puppet/provider/posix_acl/posixacl.rb#L107-L108

`perm_to_set` has x instead of X. At the end, the applied permission is x which makes all files within a directory executables.

**Comment by ekohl** [comment]
Apologies, didn't read carefully.

**Comment by ekohl** [comment]
@jadestorm could you have a look?

**Comment by jadestorm** [comment]
@ekohl Hrm.  I'll take a look but it probably won't be for a few days or even potentially weeks as things are busy at work.  Feel free to revert the PR and I'll resubmit if you want!  Regardless I'll try to take care of it asap.  =)  Thanks!

**Comment by jadestorm** [comment]
@ekohl I'm working on this right now btw --  I'll submit a second PR for the fix.  Thanks for catching this @grodriguezl !

**Comment by jadestorm** [comment]
See #65    In my tests it solved the issue.  It's not the cleanest thing in the world.
