### ISSUE TITLE
Version release

### ISSUE THREAD

**Issue by paescuj** [voxpupuli/puppet-posix_acl#67]
Do you think a version release would be possible soon?
The latest version 0.1.1 dates back to Oct 14, 2018.
We are interested particularly in https://github.com/voxpupuli/puppet-posix_acl/pull/66 as well as https://github.com/voxpupuli/puppet-posix_acl/pull/65.

## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 4.10.12
- Ruby: - 
- Distribution: CentOS 7
- Module version: 0.1.1

**Comment by ghoneycutt** [comment]
I merged a PR to add Debian 9 and 10 support and more importantly as @paescuj mentioned, this code is very old. Suggest releasing 1.0.0 as it is.

**Comment by bastelfreak** [comment]
Required modulesync before a release: https://github.com/voxpupuli/puppet-posix_acl/pull/68

**Comment by bastelfreak** [comment]
fixed by https://github.com/voxpupuli/puppet-posix_acl/pull/69

**Comment by paescuj** [comment]
Great! Thanks a lot!
