### ISSUE TITLE
Request: Publish v1.0.1 to Forge

### ISSUE THREAD

**Issue by fetzerms** [voxpupuli/puppet-posix_acl#86]
Do you think the current Tag (from January) can be published to forge? Or is there a reason not to?
Currently v1.0.0 is the most up-to-date version and we'd love to pull it from forge (rather than from github).

## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: -
- Ruby: - 
- Distribution: - 
- Module version: v1.0.1

## What behaviour did you expect instead

v1.0.1 is available via https://forge.puppet.com/modules/puppet/posix_acl

**Comment by mzohaib-elastica** [comment]
Hi, can someone please look into this request? its been pending around a month. Thanks
