### ISSUE TITLE
Oracle Linux: Warning about multiple default providers

### ISSUE THREAD

**Issue by housemasterkrause** [voxpupuli/puppet-posix_acl#88]
We are using the posix_acl module on some Oracle Linux 7 Servers.
Oracle Linux is binary compatible to RedHat Enterprise Linux or CentOS.

When i start puppet, i get the following warning message from posix_acl module:
`Info: Using configured environment 'XXXX'
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Retrieving locales
Info: Loading facts
Warning: Found multiple default providers for posix_acl: genericacl, posixacl; using genericacl
Info: Caching catalog for XXXX
Info: Applying configuration version '1623935894'
Notice: Applied catalog in 19.77 seconds`

I also set the correct provider in the puppet code where i wanna use posix_acl:
`    posix_acl { 'XXX':
      provider   => posixacl,
      action     => set,
      permission => [
        "XXX"
      ],
      require    => [
        User['XXX'],
      ],
      recursive  => true,
    }
`

How can i resolve this warning about the multiple default providers and force the module to use posic_acl?

Or can this warning be ignored cause i set the correct provider within the puppet code? 

Maybe also a bug with using posix_acl on a Oracle Linux Machine.

Thanks in advance!

**Comment by ekohl** [comment]
It doesn't select the correct default because the OS is not listed here:
https://github.com/voxpupuli/puppet-posix_acl/blob/b8f267339c00f0c62e6021a4a6abba9165f28cb0/lib/puppet/provider/posix_acl/posixacl.rb#L13
Perhaps it should move to OS families instead.

**Comment by housemasterkrause** [comment]
Is there a possibillity to fix this problem with a newer version of the script?
Than we can use it on Oracle Linux without warnings.

Thanks!

**Comment by ekohl** [comment]
You can submit a patch that changes it to `defaultfor osfamily: [:debian, :redhat, :suse, gentoo]` which I think would make it work for all RedHat-derived OSes.
