### ISSUE TITLE
Directory +x / Files not +x

### ISSUE THREAD

**Issue by Poil** [voxpupuli/puppet-posix_acl#9]
Hi

It does not seem possible to do `setfacl -R -m u:myuser:rwX myfolder`

Any idea (except no-recurse/give all subfiles) ? 

Best regards

**Comment by dobbymoodge** [comment]
So looking into this a bit further, it looks like the munging here will need to be updated: https://github.com/dobbymoodge/puppet-acl/blob/master/lib/puppet/type/acl.rb#L194

Also, either set_perm needs to test the path being set and adust perms or the perms passed to set_perm here need to be modified conditionally: https://github.com/dobbymoodge/puppet-acl/blob/master/lib/puppet/provider/acl/posixacl.rb#L114

**Comment by towo** [comment]
Bump. Still relevant.
