### ISSUE TITLE
Is the module compatible with Puppet 7.x ?

### ISSUE THREAD

**Issue by Thelvaen** [voxpupuli/puppet-posix_acl#91]
Hello,

Module is noted as compatible with Puppet >= 5.5.8 < 7.0.0 in the metadata.json.

Does the code needs some kind of rework to be compatible with Puppet < 8.0.0?

Regards,

**Comment by ekohl** [comment]
Probably not. Vox Pupuli strives to have support for Puppet 7 everywhere. Could you submit a PR to change metadata.json?

**Comment by Thelvaen** [comment]
done
